export const OPERATIONS = {
  INSERT: "INSERT",
  UPDATE: "UPDATE",
  ERROR: "ERROR",
};

export const STATUS = {
  SUCCESS: "SUCCESS",
  INCOMPLETE: "INCOMPLETE",
};

export const NEWS_CONFIG = {
  DEFAULT_MAX_ATTEMPTS: 10,
  DEFAULT_TOTAL_RECORDS: 20,
  DEFAULT_PAGE_SIZE: 500,
  FROM_DATE: "2010-01-01",
  TO_DATE: "2025-12-31",
};

export const FARMERS_CONFIG = {
  DEFAULT_MAX_ATTEMPTS: 10,
  DEFAULT_PAGE_SIZE: 500,
};

export const COMMUNITIES_CONFIG = {
  DEFAULT_MAX_ATTEMPTS: 10,
  DEFAULT_TOTAL_RECORDS: 20,
  DEFAULT_PAGE_SIZE: 500,
};

export const MERCHANTS_CONFIG = {
  DEFAULT_MAX_ATTEMPTS: 10,
  DEFAULT_PAGE_SIZE: 500,
};

export const OPERATIONS_CONFIG = {
  DEFAULT_MAX_ATTEMPTS: 10,
  DEFAULT_PAGE_SIZE: 500,
  START_YEAR: 2010,
  END_YEAR: 2025,
  FROM_DATE: "2010-01-01",
  TO_DATE: "2025-12-31",
};

export const GAP_CONFIG = {
  DEFAULT_MAX_ATTEMPTS: 10,
  DEFAULT_PAGE_SIZE: 500,
  START_YEAR: 2010,
  END_YEAR: 2025,
};

export const WATER_CONFIG = {
  DEFAULT_MAX_ATTEMPTS: 10,
  DEFAULT_PAGE_SIZE: 500,
  START_YEAR: 2010,
  END_YEAR: 2025,
};

export const SUBSTANCE_CONFIG = {
  DEFAULT_MAX_ATTEMPTS: 10,
  DEFAULT_PAGE_SIZE: 500,
  START_YEAR: 2010,
  END_YEAR: 2025,
};

export const CROPS_CONFIG = {
  DEFAULT_MAX_ATTEMPTS: 10,
  DEFAULT_PAGE_SIZE: 500,
  START_YEAR: 2010,
  END_YEAR: 2025,
};

export const DURIAN_GARDENS_CONFIG = {
  DEFAULT_MAX_ATTEMPTS: 10,
  DEFAULT_TOTAL_RECORDS: 1161,
  DEFAULT_PAGE_SIZE: 500,
};

export const PRICE_CONFIG = {
  DEFAULT_MAX_ATTEMPTS: 10,
  DEFAULT_PAGE_SIZE: 500,
  FROM_DATE: "2010-01-01",
  TO_DATE: "2025-12-31",
};
