const OPERATIONS = {
  INSERT: "INSERT",
  UPDATE: "UPDATE",
  ERROR: "ERROR",
};

const STATUS = {
  SUCCESS: "SUCCESS",
  INCOMPLETE: "INCOMPLETE",
};

const NEWS_CONFIG = {
  DEFAULT_TARGET_COUNT: 5,
  DEFAULT_MAX_ATTEMPTS: 10,
  DEFAULT_TOTAL_RECORDS: 5,
  DEFAULT_PAGE_SIZE: 500,
};

const FARMERS_CONFIG = {
  DEFAULT_TARGET_COUNT: 1114,
  DEFAULT_MAX_ATTEMPTS: 10,
  DEFAULT_TOTAL_RECORDS: 1114,
  DEFAULT_PAGE_SIZE: 500,
};

const COMMUNITIES_CONFIG = {
  DEFAULT_TARGET_COUNT: 3,
  DEFAULT_MAX_ATTEMPTS: 10,
  DEFAULT_TOTAL_RECORDS: 3,
  DEFAULT_PAGE_SIZE: 500,
};

const MERCHANTS_CONFIG = {
  DEFAULT_TARGET_COUNT: 0,
  DEFAULT_MAX_ATTEMPTS: 10,
  DEFAULT_TOTAL_RECORDS: 0,
  DEFAULT_PAGE_SIZE: 500,
};

const OPERATIONS_CONFIG = {
  DEFAULT_TARGET_COUNT: 0,
  DEFAULT_MAX_ATTEMPTS: 10,
  DEFAULT_TOTAL_RECORDS: 100,
  DEFAULT_PAGE_SIZE: 500,
  DEFAULT_CROP_YEAR: 2024,
  DEFAULT_FROM_DATE: "2024-01-01",
  DEFAULT_TO_DATE: "2024-12-31",
};

const GAP_CONFIG = {
  DEFAULT_TARGET_COUNT: 518,
  DEFAULT_MAX_ATTEMPTS: 10,
  DEFAULT_TOTAL_RECORDS: 518,
  DEFAULT_PAGE_SIZE: 500,
};

const SUBSTANCE_CONFIG = {
  DEFAULT_TARGET_COUNT: 0,
  DEFAULT_MAX_ATTEMPTS: 10,
  DEFAULT_TOTAL_RECORDS: 100,
  DEFAULT_PAGE_SIZE: 500,
};

const WATER_CONFIG = {
  DEFAULT_TARGET_COUNT: 0,
  DEFAULT_MAX_ATTEMPTS: 10,
  DEFAULT_TOTAL_RECORDS: 100,
  DEFAULT_PAGE_SIZE: 500,
};

module.exports = {
  OPERATIONS,
  STATUS,
  NEWS_CONFIG,
  FARMERS_CONFIG,
  COMMUNITIES_CONFIG,
  MERCHANTS_CONFIG,
  OPERATIONS_CONFIG,
  GAP_CONFIG,
  SUBSTANCE_CONFIG,
  WATER_CONFIG,
};
