// Mock API service for testing fetch-first approach
// Simulates API calls with controllable success/failure scenarios

/**
 * Mock API call - returns test data
 * Set shouldFail to true to simulate API failure
 */
export async function getTestMockData({ pageIndex = 1, pageSize = 10, shouldFail = false }) {
  // Simulate API failure for testing
  if (shouldFail) {
    throw new Error("Simulated API failure for testing");
  }

  // Simulate empty response for testing
  if (pageIndex > 2) {
    return {
      code: 200,
      message: "Success",
      data: [],
      totalRecords: 0,
    };
  }

  // Generate mock data
  const mockData = [];
  const recordsPerPage = Math.min(pageSize, 5); // Max 5 records per page for testing
  
  for (let i = 0; i < recordsPerPage; i++) {
    const recordNum = (pageIndex - 1) * pageSize + i + 1;
    mockData.push({
      recId: `MOCK${String(recordNum).padStart(4, '0')}`,
      name: `Test Record ${recordNum}`,
      description: `Generated by API call - Page ${pageIndex}`,
      status: recordNum % 2 === 0 ? 'active' : 'inactive',
      createdTime: new Date().toISOString().slice(0, 19).replace('T', ' '),
      updatedTime: new Date().toISOString().slice(0, 19).replace('T', ' '),
    });
  }

  return {
    code: 200,
    message: "Success",
    data: mockData,
    totalRecords: mockData.length,
  };
}

/**
 * Mock API call that always fails - for testing error handling
 */
export async function getTestMockDataFail() {
  throw new Error("Intentional API failure for testing");
}

/**
 * Mock API call that returns empty data - for testing no-data scenario
 */
export async function getTestMockDataEmpty() {
  return {
    code: 200,
    message: "Success",
    data: [],
    totalRecords: 0,
  };
}
