const mysql = require("mysql2");

const connectionDB = mysql.createConnection({
  host: process.env.DB_HOST,
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: "otod-test",
});

const cropFields = [
  "recId",
  "province",
  "farmerId",
  "title",
  "firstName",
  "lastName",
  "landId",
  "landType",
  "lat",
  "lon",
  "noOfRais",
  "noOfNgan",
  "noOfWah",
  "cropId",
  "cropYear",
  "cropName",
  "breedId",
  "breedName",
  "gapCertNumber",
  "gapCertType",
  "gapIssuedDate",
  "gapExpiryDate",
  "cropStartDate",
  "cropEndDate",
  "totalTrees",
  "forecastKg",
  "forecastBaht",
  "forecastWorkerCost",
  "forecastFertilizerCost",
  "forecastEquipmentCost",
  "forecastPetrolCost",
  "durianStageId",
  "durianStageName",
  "createdTime",
  "updatedTime",
  "companyId",
  "companyName",
];

const cropSummaryFields = [
  "provinceName",
  "cropYear",
  "breedName",
  "totalCrops",
  "totalGAPs",
  "totalTrees",
  "forecastKg",
  "forecastBaht",
  "forecastWorkerCost",
  "forecastFertilizerCost",
  "forecastEquipmentCost",
  "yieldKg",
  "yieldBaht",
];

const gapSummaryFields = [
  "provinceName",
  "cropYear",
  "breedName",
  "totalCrops",
  "totalGAPs",
  "totalActive",
  "totalExpired",
  "total6mthExpiring",
];

const cropStageSummaryFields = [
  "province",
  "cropYear",
  "totalCropsSTG1",
  "totalCropsSTG2",
  "totalCropsSTG3",
  "totalCropsSTG4",
  "totalCropsSTG5",
  "totalCropsSTG6",
  "totalCropsSTG7",
  "totalCropsSTG8",
  "totalCropsSTG9",
  "totalCropsSTG10",
  "totalCropsSTG11",
  "totalCropsSTG12",
  "totalCropsSTG13",
  "totalCropsSTG14",
  "totalCropsSTG15",
  "totalCropsSTG16",
  "totalCropsSTG17",
  "totalCropsSTG18",
];

const cropHarvestFields = [
  "provinceName",
  "cropYear",
  "farmerId",
  "title",
  "firstName",
  "lastName",
  "farmerRegistNumber",
  "landId",
  "lat",
  "lon",
  "kml",
  "cropId",
  "operId",
  "operDate",
  "lotNumber",
  "yieldKg",
  "yieldBaht",
];

const cropForecastAndYieldFields = [
  "cropYear",
  "provinceName",
  "breedName",
  "totalForecastKg",
  "totalForecastBaht",
  "totalYieldKg",
  "totalYieldBaht",
];

module.exports = {
  connectionDB,
  cropFields,
  cropSummaryFields,
  gapSummaryFields,
  cropStageSummaryFields,
  cropHarvestFields,
};
